# Generated by Django 3.0.7 on 2020-06-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='zrobione',
        ),
    ]
