# Generated by Django 3.0.7 on 2020-06-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200609_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='zrobione',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tytuł',
            new_name='title',
        ),
    ]
