# Generated by Django 3.0.7 on 2020-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200609_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='zrobione',
        ),
    ]
