# Generated by Django 3.0.7 on 2020-06-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200612_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='tytuł',
        ),
    ]
