# Generated by Django 3.0.7 on 2020-06-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200612_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tytuł',
            new_name='title',
        ),
    ]
